### ISSUE TITLE
Cannot import name 'SSHComs' from 'SSHComs'

### ISSUE THREAD

**Issue by changtraisitinh** [melvinofida/BoneScan#1]
± |master U:3 ?:4 ✗| → python3 BoneScan.py 
Traceback (most recent call last):
  File "BoneScan.py", line 1, in <module>
    from SSHComs import SSHComs
ImportError: cannot import name 'SSHComs' from 'SSHComs' (/root/Tools/BoneScan/BoneScan/SSHComs.py)

=> not lines code in SSHComs.py

**Comment by lehubbard** [comment]
The issue is resolved. I think this was a result of an error in the readme.
